version: "3"
services:
  app:
    build:
    context: ./
    image: tracrux/irelandwindfarms
    command: gunicorn wsgi:app --bind 0.0.0.0:5000
    volumes:
      - .:/flaskapp
      - ./static:/flaskapp/static
    ports:
      - "5000"

  nginx:
    image: nginx:latest
    command: rm /etc/nginx/conf.d/default.conf
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/flaskapp/static
    ports:
      - "80:80"
    depends_on:
      - app

volumes:
  static: